# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' p2type1
#'
#' p2type1 generates the probability distribution function P_{i,j}(x,y) for
#' a 2-type branching process with a single type 1 ancestor. Type 1
#' individuals split with rate alpha1, die with rate beta1 and mutate
#' to form one type 2 daughter with rate nu. Type 2 individuals
#' split with rate alpha2 and die with rate beta2.
#'
#' @param t time to run process
#' @param dom Size of domain of pdf to calculate. p2type1 calculates
#'   values of P_{i,j}(x,y) for x,y = {0, 1, ..., dom - 1}. Larger
#'   time requires higher values of dom, but slows down computation
#'   since a dom x dom matrix is created.
#' @param alpha1 type 1 split rate
#' @param beta1 type 1 death rate
#' @param nu type 1 mutation rate (Note: not a probability!)
#' @param alpha2 type 2 split rate
#' @param beta2 type 2 death rate
#' @return numeric matrix with (i,j) element representing P_{x,y}(x-1,j-1) since
#'   (0,0) is included.
#'
p2type1 <- function(t, dom, alpha1, beta1, nu, alpha2, beta2, ancestors = 1L, threads = 1L) {
    .Call(`_bdmsim_p2type1`, t, dom, alpha1, beta1, nu, alpha2, beta2, ancestors, threads)
}

#' p2type2
#'
#' p2type2 generates the probability distribution function P_{i,j}(x,y) for
#' a 2-type branching process with a single type 1 ancestor. Type 1
#' individuals split with rate alpha1, die with rate beta1 and mutate
#' to form one type 1 and one type 2 daughter with rate nu. Type 2 individuals
#' split with rate alpha2 and die with rate beta2.
#'
#' @param t time to run process
#' @param dom Size of domain of pdf to calculate. p2type2 calculates
#'   values of P_{i,j}(x,y) for x,y = {0, 1, ..., dom - 1}. Larger
#'   time requires higher values of dom, but slows down computation
#'   since a dom x dom matrix is created.
#' @param alpha1 type 1 split rate
#' @param beta1 type 1 death rate
#' @param nu type 1 mutation rate (Note: not a probability!)
#' @param alpha2 type 2 split rate
#' @param beta2 type 2 death rate
#' @return numeric matrix with (i,j) element representing P_{x,y}(x-1,j-1) since
#'   (0,0) is included.
#'
p2type2 <- function(t, dom, alpha1, beta1, nu, alpha2, beta2, ancestors = 1L, threads = 1L) {
    .Call(`_bdmsim_p2type2`, t, dom, alpha1, beta1, nu, alpha2, beta2, ancestors, threads)
}

