# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_distribution <- function(t, beta1, nu, alpha2, beta2) {
    .Call(`_sim2type_generate_distribution`, t, beta1, nu, alpha2, beta2)
}

