# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' p2type
#' 
#' p2type generates the probability distribution function P_{i,j}(x,y) for
#' a 2-type branching process with a single type 1 ancestor. Type 1
#' individuals split with rate alpha1, die with rate beta1 and mutate
#' to form one type 1 and one type 2 daughter with rate nu. Type 2 individuals
#' split with rate alpha2 and die with rate beta2.
#' 
#' @param t time to run process
#' @param alpha1 type 1 split rate
#' @param beta1 type 1 death rate
#' @param nu type 1 mutation rate (Note: not a probability!)
#' @param alpha2 type 2 split rate
#' @param beta2 type 2 death rate
#' @param domain_size Size of domain of pdf to calculate. p2type calculates
#'   values of P_{i,j}(x,y) for x,y = {0, 1, ..., 2^domain_size - 1}. Larger
#'   time requires higher values of N, but slows down computation since a
#'   2^N x 2^N matrix is created.
#' @return numeric matrix with (i,j) element representing P_{x,y}(x-1,j-1) since
#'   (0,0) is included.
#'   
p2type <- function(t, alpha1, beta1, nu, alpha2, beta2, ancestors, domain_size, threads = 0L) {
    .Call(`_sim2type_p2type`, t, alpha1, beta1, nu, alpha2, beta2, ancestors, domain_size, threads)
}

